//This file is automatically generated by h2interface.py
#include "fdlibm.h"

//The nest functions are extract by fdlibm.h
double py_acos (double x0){
	double b = acos(x0);
	return b;
}

double py_asin (double x0){
	double b = asin(x0);
	return b;
}

double py_atan (double x0){
	double b = atan(x0);
	return b;
}

double py_atan2 (double x0,double x1){
	double b = atan2(x0,x1);
	return b;
}

double py_cos (double x0){
	double b = cos(x0);
	return b;
}

double py_sin (double x0){
	double b = sin(x0);
	return b;
}

double py_tan (double x0){
	double b = tan(x0);
	return b;
}

double py_cosh (double x0){
	double b = cosh(x0);
	return b;
}

double py_sinh (double x0){
	double b = sinh(x0);
	return b;
}

double py_tanh (double x0){
	double b = tanh(x0);
	return b;
}

double py_exp (double x0){
	double b = exp(x0);
	return b;
}

double py_frexp (double x0,int* x1){
	double b = frexp(x0,x1);
	return b;
}

double py_ldexp (double x0,int x1){
	double b = ldexp(x0,x1);
	return b;
}

double py_log (double x0){
	double b = log(x0);
	return b;
}

double py_log10 (double x0){
	double b = log10(x0);
	return b;
}

double py_modf (double x0,double* x1){
	double b = modf(x0,x1);
	return b;
}

double py_pow (double x0,double x1){
	double b = pow(x0,x1);
	return b;
}

double py_sqrt (double x0){
	double b = sqrt(x0);
	return b;
}

double py_ceil (double x0){
	double b = ceil(x0);
	return b;
}

double py_fabs (double x0){
	double b = fabs(x0);
	return b;
}

double py_floor (double x0){
	double b = floor(x0);
	return b;
}

double py_fmod (double x0,double x1){
	double b = fmod(x0,x1);
	return b;
}

double py_erf (double x0){
	double b = erf(x0);
	return b;
}

double py_erfc (double x0){
	double b = erfc(x0);
	return b;
}

double py_gamma (double x0){
	double b = gamma(x0);
	return b;
}

double py_hypot (double x0,double x1){
	double b = hypot(x0,x1);
	return b;
}

int py_isnan (double x0){
	int b = isnan(x0);
	return b;
}

int py_finite (double x0){
	int b = finite(x0);
	return b;
}

double py_j0 (double x0){
	double b = j0(x0);
	return b;
}

double py_j1 (double x0){
	double b = j1(x0);
	return b;
}

double py_jn (int x0,double x1){
	double b = jn(x0,x1);
	return b;
}

double py_lgamma (double x0){
	double b = lgamma(x0);
	return b;
}

double py_y0 (double x0){
	double b = y0(x0);
	return b;
}

double py_y1 (double x0){
	double b = y1(x0);
	return b;
}

double py_yn (int x0,double x1){
	double b = yn(x0,x1);
	return b;
}

double py_acosh (double x0){
	double b = acosh(x0);
	return b;
}

double py_asinh (double x0){
	double b = asinh(x0);
	return b;
}

double py_atanh (double x0){
	double b = atanh(x0);
	return b;
}

double py_cbrt (double x0){
	double b = cbrt(x0);
	return b;
}

double py_logb (double x0){
	double b = logb(x0);
	return b;
}

double py_nextafter (double x0,double x1){
	double b = nextafter(x0,x1);
	return b;
}

double py_remainder (double x0,double x1){
	double b = remainder(x0,x1);
	return b;
}

double py_scalb (double x0,int x1){
	double b = scalb(x0,x1);
	return b;
}

double py_scalb_dd (double x0,double x1){
	double b = scalb(x0,x1);
	return b;
}

double py_significand (double x0){
	double b = significand(x0);
	return b;
}

double py_copysign (double x0,double x1){
	double b = copysign(x0,x1);
	return b;
}

int py_ilogb (double x0){
	int b = ilogb(x0);
	return b;
}

double py_rint (double x0){
	double b = rint(x0);
	return b;
}

double py_scalbn (double x0,int x1){
	double b = scalbn(x0,x1);
	return b;
}

double py_expm1 (double x0){
	double b = expm1(x0);
	return b;
}

double py_log1p (double x0){
	double b = log1p(x0);
	return b;
}

double py_gamma_r (double x0,int* x1){
	double b = gamma_r(x0,x1);
	return b;
}

double py_lgamma_r (double x0,int* x1){
	double b = lgamma_r(x0,x1);
	return b;
}

double py___ieee754_sqrt (double x0){
	double b = __ieee754_sqrt(x0);
	return b;
}

double py___ieee754_acos (double x0){
	double b = __ieee754_acos(x0);
	return b;
}

double py___ieee754_acosh (double x0){
	double b = __ieee754_acosh(x0);
	return b;
}

double py___ieee754_log (double x0){
	double b = __ieee754_log(x0);
	return b;
}

double py___ieee754_atanh (double x0){
	double b = __ieee754_atanh(x0);
	return b;
}

double py___ieee754_asin (double x0){
	double b = __ieee754_asin(x0);
	return b;
}

double py___ieee754_atan2 (double x0,double x1){
	double b = __ieee754_atan2(x0,x1);
	return b;
}

double py___ieee754_exp (double x0){
	double b = __ieee754_exp(x0);
	return b;
}

double py___ieee754_cosh (double x0){
	double b = __ieee754_cosh(x0);
	return b;
}

double py___ieee754_fmod (double x0,double x1){
	double b = __ieee754_fmod(x0,x1);
	return b;
}

double py___ieee754_pow (double x0,double x1){
	double b = __ieee754_pow(x0,x1);
	return b;
}

double py___ieee754_lgamma_r (double x0,int* x1){
	double b = __ieee754_lgamma_r(x0,x1);
	return b;
}

double py___ieee754_gamma_r (double x0,int* x1){
	double b = __ieee754_gamma_r(x0,x1);
	return b;
}

double py___ieee754_lgamma (double x0){
	double b = __ieee754_lgamma(x0);
	return b;
}

double py___ieee754_gamma (double x0){
	double b = __ieee754_gamma(x0);
	return b;
}

double py___ieee754_log10 (double x0){
	double b = __ieee754_log10(x0);
	return b;
}

double py___ieee754_sinh (double x0){
	double b = __ieee754_sinh(x0);
	return b;
}

double py___ieee754_hypot (double x0,double x1){
	double b = __ieee754_hypot(x0,x1);
	return b;
}

double py___ieee754_j0 (double x0){
	double b = __ieee754_j0(x0);
	return b;
}

double py___ieee754_j1 (double x0){
	double b = __ieee754_j1(x0);
	return b;
}

double py___ieee754_y0 (double x0){
	double b = __ieee754_y0(x0);
	return b;
}

double py___ieee754_y1 (double x0){
	double b = __ieee754_y1(x0);
	return b;
}

double py___ieee754_jn (int x0,double x1){
	double b = __ieee754_jn(x0,x1);
	return b;
}

double py___ieee754_yn (int x0,double x1){
	double b = __ieee754_yn(x0,x1);
	return b;
}

double py___ieee754_remainder (double x0,double x1){
	double b = __ieee754_remainder(x0,x1);
	return b;
}

int py___ieee754_rem_pio2 (double x0,double* x1){
	int b = __ieee754_rem_pio2(x0,x1);
	return b;
}

double py___ieee754_scalb (double x0,int x1){
	double b = __ieee754_scalb(x0,x1);
	return b;
}

double py___ieee754_scalb_dd (double x0,double x1){
	double b = __ieee754_scalb(x0,x1);
	return b;
}

double py___kernel_standard (double x0,double x1,int x2){
	double b = __kernel_standard(x0,x1,x2);
	return b;
}

double py___kernel_sin (double x0,double x1,int x2){
	double b = __kernel_sin(x0,x1,x2);
	return b;
}

double py___kernel_cos (double x0,double x1){
	double b = __kernel_cos(x0,x1);
	return b;
}

double py___kernel_tan (double x0,double x1,int x2){
	double b = __kernel_tan(x0,x1,x2);
	return b;
}

int py___kernel_rem_pio2 (double* x0,double* x1,int x2,int x3,int x4,int* x5){
	int b = __kernel_rem_pio2(x0,x1,x2,x3,x4,x5);
	return b;
}

